package com.compilador.parser;
import java_cup.runtime.*;

/*-------TERMINALES-----------*/

terminal PR_INT, PR_FLOAT, PR_BOOL, PR_CHAR, PR_STRING;
terminal PR_VOID, PR_MAIN;
terminal PR_IF, PR_ELSE, PR_WHILE, PR_DO, PR_RETURN;
terminal PR_INCLUDE, PR_STD, PR_COUT, PR_CIN;
terminal LIB_IOSTREAM;

terminal OP_SUMA, OP_RESTA, OP_MULT, OP_DIV;
terminal OP_ASIG, OP_IGUAL, OP_DIF;
terminal OP_MENOR, OP_MAYOR, OP_MENOR_IGUAL, OP_MAYOR_IGUAL;
terminal OP_AND, OP_OR, OP_NOT;

terminal PUNTO_COMA, COMA, HASH;
terminal PAREN_IZQ, PAREN_DER;
terminal LLAVE_IZQ, LLAVE_DER;

terminal String  ID;
terminal Integer LIT_ENTERO;
terminal Double  LIT_DECIMAL;
terminal String  LIT_STRING;


/*------NO TERMINALES------*/
non terminal programa;
non terminal lista_directivas, directiva;
non terminal lista_funciones, declaracion_funcion;
non terminal tipo, parametros, lista_parametros, parametro;
non terminal cuerpo_funcion;

/*----------PRECEDENCIA------------*/
precedence left OP_OR;
precedence left OP_AND;
precedence left OP_IGUAL, OP_DIF;
precedence left OP_MENOR, OP_MAYOR, OP_MENOR_IGUAL, OP_MAYOR_IGUAL;
precedence left OP_SUMA, OP_RESTA;
precedence left OP_MULT, OP_DIV;
precedence right OP_NOT;

start with programa;

programa
    ::= lista_directivas lista_funciones
    |  lista_funciones
    ;

lista_directivas
    ::= lista_directivas
    |   directiva
    ;

directiva
    ::= HASH PR_INCLUDE LT LIB_IOSTREAM GT
    |   HASH_PR_INCLUDE LT ID GT
    |   HASH PR_INCLUDE error
        {: System.err.println("Error: Directiva #include invalida en linea "
            + ((Symbol)CUP$parser$stack.peek()).left
            + ", columna " + ((Symbol)CUP$parser$stack.peek()).right); :}
        ;
    
lista_funciones 
    ::= lista_funciones declaracion_funcion
    |   declaracion_funcion
    ;

declaracion_funcion
    ::= tipo ID PAREN_IZQ parametros PAREN_DER LLAVE_IZQ cuerpo_funcion LLAVE_DER

    |  tipo PR_MAIN PAREN_IZQ parametros PAREN_DER LLAVE_IZQ cuerpo_funcion LLAVE_DER

    |  tipo ID PAREN_IZQ parametros error LLAVE_DER cuerpo_funcion LLAVE_DER
        {: System.err.println("Error: Falta '(' o ')' en declaracion de funcion en linea "
            + ((Symbol)CUP$parser$stack.peek()).left
            + ", columna " + ((Symbol)CUP$parser$stack.peek()).right); :}

    |  ID PAREN_IZQ parametros PAREN_DER LLAVE_IZQ cuerpo_funcion LLAVE_DER
        {: System.err.println("Error: Tipo de retorno invalido en linea " 
            + ((Symbol)CUP$parser$stack.peek()).left
            + ", columna " + ((Symbol)CUP$parser$stack.peek()).right); :}
    ;

tipo
    ::= PR_INT
    |   PR_FLOAT
    |   PR_BOOL
    |   PR_CHAR
    |   PR_STRING
    |   PR_VOID
    |   ID
    ;

parametros
    ::= lista_parametros
    | 
    ;

lista_parametros 
    ::= lista_parametros COMA parametro
    |   lista_parametro error parametro
        {: System.err.println("Error: Falta ',' entre parametros en linea "
            + ((Symbol)CUP$parser$stack.peek()).left
            + ", columna " + ((Symbol)CUP$parser$stack.peek()).right); :}
    |   parametro
    ;

parametro 
    ::= tipo ID
    |   tipo COMA
            {: System.err.println("Error: Parametro invalido (coma sobrante) en linea 
                + ((Symbol)CUP$parser$stack.peek()).left
                + ", columna " + ((Symbol)CUP$parser$stack.peek()).right); :}

    | tipo error 
        {: System.err.println("Error: Parametro invalido en linea " 
            + ((Symbol)CPU$parser$stack.peek()).left
            + ", columna " + ((Symbol)CUP$parser$stack.peek()).right); :}
    ;

cuerpo_funcion
    ::= 
    ;